version: "3.8"

services:

  database:
    image: mysql
    container_name: mysql-container
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "trailincalvi"
      MYSQL_USER: tic
      MYSQL_PASSWORD: tic
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'

  maildev:
    image: maildev/maildev
    container_name: maildev-container
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "1080:80"

  php:
    build:
      context: .
    container_name: php-container
    volumes:
      - ./:/var/www/trailincalvi
      - .docker/php/custom-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "9000:9000"
    environment:
        DATABASE_URL: mysql://tic:tic@mysql-container:3306/trailincalvi?serverVersion=${MYSQL_VERSION:-13}

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/trailincalvi
      - .docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

volumes:
  db-data:
